[workspace]
members = [".", "uclock-server", "uclock-cli"]

[package]
name = "uclock"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
futures = "0.3.15"
tokio = { version = "1.6.0", features = ["time"] }
